name: Publish

on:
  release:
    types: [ created ]

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository --no-configuration-cache
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: build-reports
          path: '**/build/reports/'
          retention-days: 7
